#!/bin/sh -e

[ "$#" -lt 1 ] && {
    printf "usage: %s [gopher://]example.com/foo/bar\n" "$0" >&2
    exit 1
}


nopref="${1##gopher://}"
host="${nopref%%/*}"
path="${nopref#"$host"}"
printf "%s\r\n" "$path" | ./nc "$host" 70
